framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # Cache configuration for validation framework
    cache:
        pools:
            cache.validation:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600 # 1 hour
                
            cache.validation_rules:
                adapter: cache.adapter.filesystem  
                default_lifetime: 3600 # 1 hour for validation rule caching

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@prod:
    framework:
        cache:
            pools:
                cache.validation:
                    # Use APCu in production for better performance
                    adapter: cache.adapter.apcu
                    default_lifetime: 3600
                    
                cache.validation_rules:
                    adapter: cache.adapter.apcu
                    default_lifetime: 3600

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file