parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Constraint/'

    # Validation Services Configuration
    App\Service\ValidationCircuitBreaker:
        arguments:
            $logger: '@monolog.logger.security'
            $failureThreshold: 5
            $recoveryTimeout: 60
            $testRequestTimeout: 30

    App\Service\ValidationService:
        arguments:
            $validator: '@validator'
            $circuitBreaker: '@App\Service\ValidationCircuitBreaker'
            $cache: '@cache.validation_rules'
            $logger: '@monolog.logger.security'

    # Constraint Validators (auto-discovered by Symfony)
    App\Constraint\SafeSurveyTextValidator:
        tags: ['validator.constraint_validator']
        
    App\Constraint\ValidSurveyQuestionValidator:
        tags: ['validator.constraint_validator']
        
    App\Constraint\SafeFileUploadValidator:
        tags: ['validator.constraint_validator']
        
    App\Constraint\ValidSurveyEmailValidator:
        tags: ['validator.constraint_validator']
        
    App\Constraint\InputLengthLimitsValidator:
        tags: ['validator.constraint_validator']
        
    App\Constraint\RateLimitValidator:
        tags: ['validator.constraint_validator']
        
    App\Constraint\SafeCharacterSetValidator:
        tags: ['validator.constraint_validator']