name: AI – Auto Progress

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled, opened]
  workflow_dispatch:

concurrency:
  group: auto-progress-${{ github.event.issue.number || github.event.pull_request.number }}-${{ github.event.label.name || '' }}
  cancel-in-progress: false

jobs:
  auto-progress:
    if: >-
      ${{
        !contains(github.event.issue.labels.*.name, 'auto:inline') &&
        (!github.event.pull_request || !contains(github.event.pull_request.labels.*.name, 'auto:inline')) &&
        (github.event_name == 'workflow_dispatch' ||
         (github.event.label && startsWith(github.event.label.name, 'state:')) ||
         (github.event_name == 'pull_request' && github.event.action == 'opened'))
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dpeuscher
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Trigger next AI step
        env:
          CI_PROVIDER: github
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
          FORGEJO_BASE_URL: ${{ secrets.FORGEJO_BASE_URL }}
          ISSUE_OR_PR_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
          EVENT_KIND: ${{ github.event_name }}
          LABEL_NAME: ${{ github.event.label.name || '' }}
          ENABLE_AGENT_AUTO_PROGRESS: 0
          AUTO_PROGRESS_BY_LABEL: 1
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        run: |
          docker run --rm \
            -e CI_PROVIDER \
            -e GH_TOKEN \
            -e FORGEJO_TOKEN \
            -e FORGEJO_BASE_URL \
            -e ISSUE_OR_PR_NUMBER \
            -e EVENT_KIND \
            -e LABEL_NAME \
            -e ENABLE_AGENT_AUTO_PROGRESS \
            -e AUTO_PROGRESS_BY_LABEL \
            -e REPO_URL \
            ghcr.io/dpeuscher/claude-code-agent:latest 