# TEMPLATE – Enable in consumer repo only
name: Claude – Approve If OK

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number to approve'
        required: true
        type: string

concurrency:
  group: claude-approve-if-ok-${{ github.event.pull_request.number || github.event.inputs.pr_number }}-${{ github.event.label.name || 'manual' }}
  cancel-in-progress: true

jobs:
  approve-pr-github:
    if: ${{ startsWith(github.server_url, 'https://github.com') &&  !contains(github.event.issue.labels.*.name, 'auto:inline') && ((github.event.action == 'labeled' && github.event.label.name == 'ai:step-12:approve-if-ok') || github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dpeuscher
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Claude – approve PR if OK (GitHub)
        env:
          CI_PROVIDER: github
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          MODE: approve_if_ok
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.check_suite.pull_requests[0].number || github.event.inputs.pr_number }}
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
          # Provider-specific credentials
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
          FORGEJO_BASE_URL: ${{ secrets.FORGEJO_BASE_URL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          LINEAR_TOKEN: ${{ secrets.LINEAR_TOKEN }}
        run: |
          docker run --rm \
            -e CI_PROVIDER \
            -e GH_TOKEN \
            -e REPO_URL \
            -e MODE \
            -e PR_NUMBER \
            -e CLAUDE_CREDENTIALS_B64 \
            -e FORGEJO_TOKEN \
            -e FORGEJO_BASE_URL \
            -e JIRA_TOKEN \
            -e JIRA_BASE_URL \
            -e LINEAR_TOKEN \
            ghcr.io/dpeuscher/claude-code-agent:latest

  approve-pr-forgejo:
    if: ${{ !startsWith(github.server_url, 'https://github.com') && ((github.event.action == 'labeled' && github.event.label.name == 'ai:step-12:approve-if-ok') || github.event_name == 'workflow_dispatch') }}
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dpeuscher
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Claude – approve PR if OK (Forgejo)
        env:
          CI_PROVIDER: forgejo
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
          FORGEJO_BASE_URL: ${{ secrets.FORGEJO_BASE_URL }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          MODE: approve_if_ok
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.check_suite.pull_requests[0].number || github.event.inputs.pr_number }}
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
          # Provider-specific credentials
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          LINEAR_TOKEN: ${{ secrets.LINEAR_TOKEN }}
        run: |
          docker run --rm \
            -e CI_PROVIDER \
            -e FORGEJO_TOKEN \
            -e FORGEJO_BASE_URL \
            -e REPO_URL \
            -e MODE \
            -e PR_NUMBER \
            -e CLAUDE_CREDENTIALS_B64 \
            -e GH_TOKEN \
            -e JIRA_TOKEN \
            -e JIRA_BASE_URL \
            -e LINEAR_TOKEN \
            ghcr.io/dpeuscher/claude-code-agent:latest 
