name: Debug – Echo Credentials (TEST ONLY)

on:
  workflow_dispatch:

jobs:
  debug-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Claude Credentials (Base64 encoded)
        env:
          CLAUDE_CREDENTIALS_B64: ${{ secrets.CLAUDE_CREDENTIALS_B64 }}
        run: |
          echo "CLAUDE_CREDENTIALS_B64 (base64 encoded to avoid censoring):"
          echo "$CLAUDE_CREDENTIALS_B64" | base64
          echo ""
          echo "Original length: ${#CLAUDE_CREDENTIALS_B64}"
          echo "Base64 encoded length: $(echo "$CLAUDE_CREDENTIALS_B64" | base64 | wc -c)"
